### ISSUE TITLE
Need to change the contact info 

### ISSUE THREAD

**Issue by akashkroy** [OpenApprenticeFoundation/openapprentice-website#38]
Change the OA emails to : admin@openapprentice.org and admin@openapprentice.org

**Comment by Seluj78** [comment]
Where ?

**Comment by akashkroy** [comment]
https://github.com/OpenApprenticeFoundation

**Comment by Seluj78** [comment]
![screenshot_20180618-203252](https://user-images.githubusercontent.com/4641317/41555059-d46458e4-7336-11e8-8d7c-a5c63bc74b08.jpg)
Done my good sir
