### ISSUE TITLE
Change copyright

### ISSUE THREAD

**Issue by Seluj78** [OpenApprenticeFoundation/openapprentice-website#39]
https://github.com/OpenApprenticeFoundation/openapprentice-website/blob/32b7d4f9c220eeebbccf1f2212d0572824c0576a/openapprentice/utils.py#L1-L29

**Comment by davidkartuzinski** [comment]
I suggested in the review of your pull request, that we change "David Kartuzinski" to "OpenApprentice Foundation"  - I really want to make this about the group as a group - which includes "David Kartuzinski", but is not "David Kartuzinski".  It's Jules, Roy, Prats, etc...

**Comment by Seluj78** [comment]
Reopened because fixed in branch that is not merged.
