### ISSUE TITLE
Set up Email server to give founding and managing members an email address

### ISSUE THREAD

**Issue by davidkartuzinski** [OpenApprenticeFoundation/openapprentice-website#4]
Server needs to get working with the email server. We had trouble look for help.

**Comment by Seluj78** [comment]
@akashkroy do you have access to `openapprentice`'s servers ? If yes can you look into setting up emails ?

**Comment by akashkroy** [comment]
I have. 

I will setup a full fledged mail server.

**Comment by Seluj78** [comment]
Great ! Will we have access to the SMTP too so I can receive and send emails with my `openapprentice` account from gmail ?

Please let us know how it goes here :D

**Comment by akashkroy** [comment]
I think thats possible :)

**Comment by Seluj78** [comment]
Done, thanks to @akashkroy :taco:
