### ISSUE TITLE
Wireframe and agree to pages, navigation and basic content structure

### ISSUE THREAD

**Issue by davidkartuzinski** [OpenApprenticeFoundation/openapprentice-website#5]
Full wire-framing of the initial wireframe for the openapprentice.org website

**Comment by Seluj78** [comment]
I can work on a wireframe with `flask` really quickly. I just need your green light to start working on that right away, or wait until you push your flask version of the website.

**Comment by davidkartuzinski** [comment]
It will probably be as fast if I though up a wireframe in HTML and then you make that into a Flask app, but I think it's easy enough to layout the basic routes in Flask as I am doing.  But thank you.

**Comment by Seluj78** [comment]
@davidkartuzinski any news on that html wireframe so I can start working on it?

**Comment by davidkartuzinski** [comment]
This has been resolved.
