### ISSUE TITLE
Admin Dashboard - Remove password confirmation ?

### ISSUE THREAD

**Issue by Seluj78** [OpenApprenticeFoundation/openapprentice-website#69]
@davidkartuzinski @Vigasaurus @akashkroy @shenoyprath123 This is the admin dashboard page to create a new user. Should I remove the repeat password for admins too ?

![image](https://user-images.githubusercontent.com/4641317/41909095-7127fa86-7946-11e8-9dcf-be6325238ab1.png)

**Comment by Vigasaurus** [comment]
I think so, yeah. We don't need them anywhere on the site.

**Comment by akashkroy** [comment]
Yeah sure , same for everyone

**Comment by davidkartuzinski** [comment]
Yes please. There is definitely no need to have admins double entry passwords.
