### ISSUE TITLE
Add markdown support to display in the frontend

### ISSUE THREAD

**Issue by Seluj78** [OpenApprenticeFoundation/openapprentice-website#74]
https://pythonhosted.org/Flask-Markdown/

**Comment by Seluj78** [comment]
Will be done using external files loaded

**Comment by davidkartuzinski** [comment]
Could you please explain the scenario where we would have markdown displayed on the Front-End?

**Comment by Seluj78** [comment]
The Idea was to use markdown files to be displayed on certain pages.

Example:

Page `/teachers` will load and display the markdown page `teachers.md`
Usefull ? I think so. I'd rather use markdown than HTML **BUT** using makdown will make it so we can only have content, no buttons etc

**Comment by Seluj78** [comment]
Closed as not relevent/stale for now.
