### ISSUE TITLE
Email confirmation to register to newsletter

### ISSUE THREAD

**Issue by Seluj78** [OpenApprenticeFoundation/openapprentice-website#91]
Should user receive a confirmation email to confirm they want to subscribe to the newsletter?

@davidkartuzinski @akashkroy @shenoyprath123 @Vigasaurus 

Refers to #87

**Comment by akashkroy** [comment]
Yeah Of course,

**Comment by Seluj78** [comment]
The others ?

**Comment by Vigasaurus** [comment]
I think so, yeah.
